services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blogs/app
    depends_on:
      - db
    volumes:
      - home:/home/
      - mysql:/var/lib/mysql/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: blogs/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - home:/home/:ro

  db:
    build:
       context: ./db
       dockerfile: Dockerfile
    image: blogs/db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
      - ./db/migration.sql:/docker-entrypoint-initdb.d/migration.sql:ro
#                                  ^ ig mysql image will run sql files inside this dir
volumes:
  mysql:
  home:
