services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blogs/app
    depends_on:
      - db
    volumes:
      - mysql:/var/lib/mysql/
      - app-home:/home/
      - app-scripts:/scripts/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: blogs/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app-home:/home/:ro

  db:
    build:
       context: ./db
       dockerfile: Dockerfile
    image: blogs/db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  app-home:
  app-scripts:
