services:
  users:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blog-server/users
    volumes:
      - home:/home/
      - mysql:/var/lib/mysql/

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: blog-server/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - home:/home/:ro

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  home:
