services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    image: blogs/app
    depends_on:
      - db
    volumes:
      - mysql:/var/lib/mysql/
      - app-home:/home/
      - app-scripts:/scripts/
    mem_limit: 512m
    cpus: 0.5

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: blogs/nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - app-home:/home/:ro
    mem_limit: 256m
    cpus: 0.3

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    healthcheck:
      test: bash -c 'mysqladmin -uroot -p"$MYSQL_ROOT_PASSWORD" ping'
      retries: 5
      interval: 5s
    image: blogs/db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    mem_limit: 1g
    cpus: 1.0

  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    image: blogs/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    mem_limit: 256m
    cpus: 0.2

volumes:
  mysql:
  app-home:
  app-scripts:
